apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
    chart: neo4j-1.2.1
    component: core
    heritage: Tiller
    release: neo4j
  name: neo4j-neo4j
  namespace: neo4j
spec:
  ports:
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  selector:
    app: neo4j
    component: core
    release: neo4j
  sessionAffinity: None
  type: LoadBalancer
