apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data
  namespace: codequality
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
