apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: codequality
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: remove-lost-found
        image: alpine:3.8
        command:
        - /bin/sh
        - -c
        - rm -rfv /var/lib/postgresql/data/lost+found
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
          readOnly: false
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
